/**:
  ros__parameters:
    # PointCloud2: fixed lidar requires no yaw motion compensation.
    xfer_format: 0
    multi_topic: 0
    data_src: 0
    publish_freq: 20.0
    output_data_type: 0
    frame_id: livox_frame

