schema_version: 2
models:
  - name: base_open_fixed
    input_mesh: ../../dart_vision_lidar_model/models/raw/armor_pnx.STL
    output_pcd: ../../dart_vision_lidar_model/models/processed/base_open_fixed.pcd
    scale_to_m: 0.001
    sample_count: 100000
    random_seed: 7001
    voxel_leaf_m: 0.02
    overwrite: true

  - name: base_closed_fixed
    input_mesh: ../../dart_vision_lidar_model/models/raw/base_pnx.STL
    output_pcd: ../../dart_vision_lidar_model/models/processed/base_closed_fixed.pcd
    scale_to_m: 0.001
    sample_count: 100000
    random_seed: 7002
    voxel_leaf_m: 0.02
    overwrite: true

  - name: moving_armor
    input_mesh: ../../dart_vision_lidar_model/models/raw/armor_pnx.STL
    output_pcd: ../../dart_vision_lidar_model/models/processed/moving_armor.pcd
    scale_to_m: 0.001
    sample_count: 5000
    random_seed: 7003
    voxel_leaf_m: 0.03
    overwrite: true
