<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dart_bringup</name>
  <version>0.0.0</version>
  <description>Launch and parameter configuration for the dart perception system.</description>
  <maintainer email="fzhang859@connect.hkust-gz.edu.cn">pnx</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>dart_description</exec_depend>
  <exec_depend>dart_serial</exec_depend>

  <exec_depend>hik_camera_driver</exec_depend>
  <exec_depend>dart_camera</exec_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
