<?xml version="1.0"?>
<package format="3">
  <name>dart_stereo</name>
  <version>0.0.0</version>
  <description>Calibrated green-light stereo geometry.</description>
  <maintainer email="fzhang859@connect.hkust-gz.edu.cn">pnx</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>dart_interfaces</depend>
  <depend>libopencv-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
