/**:
  ros__parameters:
    device: /dev/ttyACM0
    baud_rate: 115200
    read_timeout_ms: 100
    reconnect_interval_ms: 1000

    send_topic: aim_command
    receive_topic: controller_state

    joint_state_topic: joint_states
    yaw_joint_name: launcher_yaw_joint

    motor_to_joint_sign: 1.0
    motor_zero_rad: 0.0
    command_timeout_s: 0.2
