cmake_minimum_required(VERSION 3.8)
project(dart_aiming)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_python_install_package(${PROJECT_NAME})
install(PROGRAMS scripts/dart_aiming_node DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(dart_aiming_core ${CMAKE_CURRENT_SOURCE_DIR}/../../tests/test_geometry_and_policy.py)
endif()
ament_package()
