<?xml version="1.0"?>
<package format="3">
  <name>dart_vision_lidar_localization</name>
  <version>0.1.0</version>
  <description>Real-time Mid-70 base, armor plate, and green-light point-cloud localization.</description>
  <maintainer email="fzhang859@connect.hkust-gz.edu.cn">pnx</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>dart_vision_interfaces</depend>
  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>libpcl-all-dev</depend>
  <depend>livox_interfaces</depend>
  <depend>pcl_conversions</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
